### ISSUE TITLE
Working with a free plan

### ISSUE THREAD

**Issue by moneya** [digikraaft/laravel-paystack-subscription#1]
This is not an issue but needed help with using your package , and I don't know the best channel to reach out to you.
Thanks for this package.
Hello @digikraaft.
I would like to know how to manage or create a free plan subscription using this your wonderful package.

Is there a way, I can handle or set a default plan for a user when subscription fails or a subscription is cancelled?.

**Comment by timoladoyinbo** [comment]
Hello @moneya,

The subscription billing is closely tied to Paystack's subscription feature which as far as I know does not support free plans out of the box. I'll look into this over the weekend to see if I can work something out to address this.

Regards.

**Comment by moneya** [comment]
Thank you...

**Comment by moneya** [comment]
@timoladoyinbo 
Good day, hope you are good.
Have you made any success chief?

**Comment by timoladoyinbo** [comment]
Hello, @moneya apologies for responding late. I had issues with getting notifications from here, which I've now fixed.

I've had some thoughts about this but can't seem to find a way around it just yet. Like I mentioned earlier, Paystack doesn't support free plans yet and this package is closely tied to Paystack's subscription feature. 

Some of the solutions I thought of would require a rewrite of this package to make it less dependent on Paystack for which I think would qualify for a new package entirely.

To address your concern, I think this might help: by default why not make features in your app available to non-subscribing users (using the subscription check of the package) such that if a subscription fails (the user is still subscribed to the plan, with an inactive subscription) the default features will then be available to the user. Not sure if this fits your workflow.

I do hope this helps.

You can also reach me on twitter @tim_oladoyinbo

Regards

**Comment by moneya** [comment]
Thanks for your time @timoladoyinbo 
Sorry I couldn't get back to you on time cause I was Ill.
