### ISSUE TITLE
Undefined variable: paystackId when trying to retrieve user's subscription status

### ISSUE THREAD

**Issue by Thomasosho** [digikraaft/laravel-paystack-subscription#3]
I get the error when i'm trying to retrieve a user's subscription status.

**Comment by timoladoyinbo** [comment]
Hello @Thomasosho , thanks for using our package. 

Can you please specify which of the methods you called that gave this error? [Here](https://github.com/digikraaft/laravel-paystack-subscription#checking-subscription-status) are the available methods that can query a user's subscription status.

Regards.

**Comment by Thomasosho** [comment]
```
if ($user->subscribedToPlan(['PLN_uqicl68u6pq9qyl', 'PLN_pmgc1t08ff3kwwr', 'PLN_pklwcpsl3s6odjf'], 'default')) {
                    $sub = Auth::user()->id;
                }
                dd($sub);
```

I'm getting 
```
Error
Call to a member function subscribedToPlan() on int
```

This is the one i'm using.

**Comment by Thomasosho** [comment]
solved

```
if (auth()->user()->subscribedToPlan(['PLN_uqicl68u6pq9qyl', 'PLN_pmgc1t08ff3kwwr', 'PLN_pklwcpsl3s6odjf'], 'default')) {
                    $sub = Auth::user()->id;
                }
```
