### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by Harrison-Idornigie** [digikraaft/laravel-paystack-subscription#5]
Hi, I am getting errors when trying to install package in Laravel 8, some dependency issues. Please update it. Thanks

**Comment by timoladoyinbo** [comment]
It already supports Laravel 8. What PHP version are you using? If you're using PHP 8 then there is already a new tag [here](https://github.com/digikraaft/laravel-paystack-subscription/releases/tag/v1.3.0), just update via composer.

**Comment by Harrison-Idornigie** [comment]
Thanks for your response. There are dependency issues when I try to install it in Laravel 8, php 7.4

**Comment by timoladoyinbo** [comment]
This has been tested in Laravel 8 and PHP 7.4 so it may not be an issue with the package. Can you share the exact installation errors you are getting?

**Comment by Harrison-Idornigie** [comment]
I just tried it now and it works. Thanks for your response

On a side note, how can I check if a user is subscribed to any plan if I have 4 plans for example? 

[https://github.com/digikraaft/laravel-paystack-subscription#checking-subscription-status](url)

The example above shows I must add a plan name. What happens if I have multiple plans and just need to check if he is subscribed to any?

**Comment by Harrison-Idornigie** [comment]
![image](https://user-images.githubusercontent.com/17069783/153427862-32264fba-08a3-41a1-a9d7-a663de428c9c.png)

The installation instructions after composer require all throw errors

**Comment by Harrison-Idornigie** [comment]
Please, help a brother, How do I pass metadata into the data object of an
API post request?

**Comment by timoladoyinbo** [comment]
> I just tried it now and it works. Thanks for your response
> 
> On a side note, how can I check if a user is subscribed to any plan if I have 4 plans for example?
> 
> [https://github.com/digikraaft/laravel-paystack-subscription#checking-subscription-status](url)
> 
> The example above shows I must add a plan name. What happens if I have multiple plans and just need to check if he is subscribed to any?

First, you don't have to add a plan name to check for a subscription status, the second argument to the `->subscribed()` function can be null.

Secondly the function you need to check for multiple plans is `->subscribedToPlan()` - the first argument can take in an array of plan codes. Read the checking subscription status section again for clarity.

**Comment by timoladoyinbo** [comment]
> Please, help a brother, How do I pass metadata into the data object of an API post request?
> […](#)

You will have to be more specific on this. But it depends on the method you're using. Generally you can pass additional data by passing an array containing your data as the third argument of most functions. Make sure the data is supported by the Paystack API.
[Read here](https://github.com/digikraaft/laravel-paystack-subscription#additional-details)

**Comment by timoladoyinbo** [comment]
I'm closing this now since the main issue raised has been resolved.

**Comment by Harrison-Idornigie** [comment]
https://github.com/digikraaft/laravel-paystack-subscription-demo/blob/master/resources/views/billing_plans.blade.php

Please help me with adding meta-data to the script tag on this form.
