### ISSUE TITLE
Problem With Publishing Config File

### ISSUE THREAD

**Issue by oladejihenry** [digikraaft/laravel-paystack-subscription#9]
After installing the package i tried running this command.

```
php artisan vendor:publish --provider="Digikraaft\PaystackSubscritpion\PaystackSubscritpionServiceProvider" --tag="config"
```

Nothing is being published, i am not sure why this happen

Also is the package still being maintained ??

**Comment by timoladoyinbo** [comment]
Hi @oladejihenry thanks for pointing this out, I'll check it. I'll be updating the package in a couple of weeks.

**Comment by timoladoyinbo** [comment]
Hello @oladejihenry  the issue was a typo in the publishing commands. I've updated the readme to reflect the correction.
